[package]
name = "color_bruteforcer"
version = "1.1.0"
authors = ["Torsten Ostgard"]
license = "MIT"
edition = "2018"

[[bin]]
doc = false
path = "src/main.rs"
name = "color_bruteforcer"

[dependencies]
clap = "2"
palette = "0.4"
pbr = "1"
promptly = "0.1"
rayon = "1"
regex = "1"
